### ISSUE TITLE
Configure conflict behaviour

### ISSUE THREAD

**Issue by bnour-corrae** [Angelin01/pod-director#17]
Configure what happens when `pod-director` encounters a conflict when assigning a selector to a pod that already has a key that `pod-director` wants to change.

For example, let's say a pod has a "foo=bar" selector, but the config says it should have a "foo=xyzzy" selector, what do we do then?
Well, let's make this behaviour configurable!

The config should have a "conflict" or "onConflict" field, or something similar.
Some ideas for the conflict resolution behaviour:
- Just override the value
- Ignore the value and keep going
- Crash and burn when encountering a conflict and reject any changes

**Comment by Angelin01** [comment]
Feature creep: do you mind updating the config separator to be just `_` instead of `__`, since you are already messing with it? It will require editing a few tests, but it's nothing major.

**Comment by bnour-corrae** [comment]
Not at all! I'll update it.
